import type { Chore } from "./types";

/**
 * Canonical chore library. Templates and pages reference these ids; do not
 * duplicate chore strings elsewhere. Keep ids stable — they appear in share
 * URLs and saved wheels.
 */
export const CHORES: Chore[] = [
  // ---- Kitchen ---------------------------------------------------------
  {
    id: "wash-dishes",
    name: "Wash dishes",
    category: "kitchen",
    frequency: "daily",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
    description: "Wash, rinse and rack everything left in the sink; wipe the sink after.",
  },
  {
    id: "load-dishwasher",
    name: "Load the dishwasher",
    category: "kitchen",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Scrape plates, load, run when full.",
  },
  {
    id: "unload-dishwasher",
    name: "Unload the dishwasher",
    category: "kitchen",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Put everything away. Little kids can handle plastics and the cutlery tray.",
  },
  {
    id: "wipe-counters",
    name: "Wipe kitchen counters",
    category: "kitchen",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Clear, spray, wipe. Move the small appliances once a week.",
  },
  {
    id: "clean-stovetop",
    name: "Clean the stovetop",
    category: "kitchen",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "teen",
    description: "Remove grates or knobs, degrease, wipe dry.",
  },
  {
    id: "clean-microwave",
    name: "Clean the microwave",
    category: "kitchen",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Steam a bowl of water for two minutes, then wipe the softened splatter.",
  },
  {
    id: "clean-fridge",
    name: "Clean the refrigerator",
    category: "kitchen",
    frequency: "monthly",
    effort: "long",
    description: "Toss expired food, remove shelves, wash, dry, restock.",
  },
  {
    id: "clean-oven",
    name: "Clean the oven",
    category: "kitchen",
    frequency: "monthly",
    effort: "long",
    description: "Use oven cleaner or a baking-soda paste; keep the room ventilated.",
  },
  {
    id: "take-out-trash",
    name: "Take out the trash",
    category: "kitchen",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Bag it, bin it, replace the liner.",
  },
  {
    id: "take-out-recycling",
    name: "Take out the recycling",
    category: "kitchen",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Rinse containers, flatten boxes, out to the bin.",
  },
  {
    id: "sweep-kitchen",
    name: "Sweep the kitchen floor",
    category: "kitchen",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Under the table and along the base of the cabinets.",
  },
  {
    id: "mop-kitchen",
    name: "Mop the kitchen floor",
    category: "kitchen",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
    description: "Sweep first. Work backward toward the door.",
  },
  {
    id: "empty-compost",
    name: "Empty the compost bin",
    category: "kitchen",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "clean-sink",
    name: "Scrub the kitchen sink",
    category: "kitchen",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Scrub, rinse, and clean the drain strainer.",
  },
  {
    id: "wipe-appliances",
    name: "Wipe appliance fronts",
    category: "kitchen",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Fridge, dishwasher, oven door, handles.",
  },
  {
    id: "organize-pantry",
    name: "Tidy the pantry",
    category: "kitchen",
    frequency: "monthly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
    description: "Check dates, group like items, wipe shelves.",
  },
  {
    id: "set-table",
    name: "Set the table",
    category: "kitchen",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "clear-table",
    name: "Clear the table",
    category: "kitchen",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  { id: "cook-dinner", name: "Cook dinner", category: "kitchen", frequency: "daily", effort: "long", kidFriendly: true, minAge: "teen" },
  { id: "plan-meals", name: "Plan the week's meals", category: "kitchen", frequency: "weekly", effort: "medium" },
  { id: "grocery-shopping", name: "Do the grocery shopping", category: "kitchen", frequency: "weekly", effort: "long" },

  // ---- Bathroom --------------------------------------------------------
  {
    id: "clean-toilet",
    name: "Clean the toilet",
    category: "bathroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "teen",
    description: "Brush the bowl, wipe seat, lid, rim and base.",
  },
  {
    id: "clean-shower",
    name: "Clean the shower or tub",
    category: "bathroom",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "teen",
    description: "Spray, wait, scrub walls and floor, rinse. A daily squeegee makes this easy.",
  },
  {
    id: "clean-bathroom-sink",
    name: "Clean the bathroom sink",
    category: "bathroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Basin, faucet, and the counter around it.",
  },
  {
    id: "clean-mirror",
    name: "Clean the mirror",
    category: "bathroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "mop-bathroom",
    name: "Mop the bathroom floor",
    category: "bathroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "restock-toilet-paper",
    name: "Restock toilet paper",
    category: "bathroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "change-towels",
    name: "Swap out bath towels",
    category: "bathroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "empty-bathroom-trash",
    name: "Empty the bathroom trash",
    category: "bathroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "wash-bath-mat",
    name: "Wash the bath mat",
    category: "bathroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  { id: "clean-grout", name: "Scrub tile grout", category: "bathroom", frequency: "monthly", effort: "long" },
  {
    id: "descale-showerhead",
    name: "Descale the showerhead and taps",
    category: "bathroom",
    frequency: "monthly",
    effort: "quick",
    description: "Soak in vinegar for an hour, rinse.",
  },

  // ---- Bedroom ---------------------------------------------------------
  { id: "make-bed", name: "Make the bed", category: "bedroom", frequency: "daily", effort: "quick", kidFriendly: true, minAge: "younger" },
  {
    id: "change-sheets",
    name: "Change the bed sheets",
    category: "bedroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "tidy-bedroom",
    name: "Tidy the bedroom",
    category: "bedroom",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Clothes in the hamper, toys and books back where they live.",
  },
  {
    id: "vacuum-bedroom",
    name: "Vacuum the bedroom",
    category: "bedroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "dust-bedroom",
    name: "Dust bedroom surfaces",
    category: "bedroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  { id: "declutter-closet", name: "Declutter the closet", category: "bedroom", frequency: "occasional", effort: "long" },
  { id: "flip-mattress", name: "Rotate the mattress", category: "bedroom", frequency: "occasional", effort: "quick" },
  {
    id: "put-away-clothes",
    name: "Put away clean clothes",
    category: "bedroom",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },

  // ---- Living areas ----------------------------------------------------
  {
    id: "vacuum-living-room",
    name: "Vacuum the living room",
    category: "living",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "dust-furniture",
    name: "Dust the furniture",
    category: "living",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Shelves, TV stand, tables, picture frames — top to bottom.",
  },
  {
    id: "tidy-living-room",
    name: "Tidy the living room",
    category: "living",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Cushions, blankets, remotes, stray cups.",
  },
  {
    id: "wipe-surfaces",
    name: "Wipe down surfaces",
    category: "living",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Tables, light switches, door handles, remote controls.",
  },
  {
    id: "water-plants",
    name: "Water the plants",
    category: "living",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "clean-windows-inside",
    name: "Clean the inside of the windows",
    category: "living",
    frequency: "monthly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "vacuum-sofa",
    name: "Vacuum the sofa",
    category: "living",
    frequency: "monthly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Lift the cushions. Crumbs, coins, hair ties.",
  },
  {
    id: "organize-shoes",
    name: "Organize the shoe area",
    category: "living",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "clean-baseboards",
    name: "Wipe the baseboards",
    category: "living",
    frequency: "monthly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
  },
  { id: "dust-blinds", name: "Dust blinds and curtains", category: "living", frequency: "monthly", effort: "medium" },
  {
    id: "tidy-entryway",
    name: "Tidy the entryway",
    category: "living",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Coats hung, shoes paired, mail sorted.",
  },

  // ---- Laundry ---------------------------------------------------------
  {
    id: "wash-laundry",
    name: "Wash a load of laundry",
    category: "laundry",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Sort, load, detergent, start. The machine does the work.",
  },
  {
    id: "dry-laundry",
    name: "Dry or hang the laundry",
    category: "laundry",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "fold-laundry",
    name: "Fold the laundry",
    category: "laundry",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "younger",
    description: "Younger kids can pair socks and fold towels.",
  },
  {
    id: "iron-clothes",
    name: "Iron clothes",
    category: "laundry",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "teen",
  },
  {
    id: "clean-lint-trap",
    name: "Clean the dryer lint trap",
    category: "laundry",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
    description: "Every load ideally — a full trap is a fire risk.",
  },
  {
    id: "wash-towels",
    name: "Wash the towels",
    category: "laundry",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "wash-bedding",
    name: "Wash the bedding",
    category: "laundry",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
  },

  // ---- Outdoor ---------------------------------------------------------
  { id: "mow-lawn", name: "Mow the lawn", category: "outdoor", frequency: "weekly", effort: "long", kidFriendly: true, minAge: "teen" },
  {
    id: "rake-leaves",
    name: "Rake the leaves",
    category: "outdoor",
    frequency: "occasional",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "water-garden",
    name: "Water the garden",
    category: "outdoor",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  { id: "pull-weeds", name: "Pull weeds", category: "outdoor", frequency: "weekly", effort: "medium", kidFriendly: true, minAge: "school" },
  {
    id: "sweep-porch",
    name: "Sweep the porch or patio",
    category: "outdoor",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "bins-to-curb",
    name: "Put the bins out for collection",
    category: "outdoor",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "bins-back",
    name: "Bring the bins back in",
    category: "outdoor",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  { id: "wash-car", name: "Wash the car", category: "outdoor", frequency: "monthly", effort: "long", kidFriendly: true, minAge: "school" },
  {
    id: "clean-gutters",
    name: "Clear the gutters",
    category: "outdoor",
    frequency: "occasional",
    effort: "long",
    description: "Adults only — ladder work.",
  },
  {
    id: "shovel-snow",
    name: "Shovel snow or salt the path",
    category: "outdoor",
    frequency: "occasional",
    effort: "medium",
    kidFriendly: true,
    minAge: "teen",
  },
  { id: "clean-grill", name: "Clean the grill", category: "outdoor", frequency: "occasional", effort: "medium" },
  {
    id: "wipe-outdoor-furniture",
    name: "Wipe the outdoor furniture",
    category: "outdoor",
    frequency: "monthly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },

  // ---- Whole home / general -------------------------------------------
  {
    id: "vacuum-floors",
    name: "Vacuum the floors",
    category: "general",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "mop-floors",
    name: "Mop the floors",
    category: "general",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "empty-all-bins",
    name: "Empty all the small bins",
    category: "general",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  {
    id: "clean-kitchen",
    name: "Clean the kitchen",
    category: "general",
    frequency: "weekly",
    effort: "long",
    kidFriendly: true,
    minAge: "teen",
    description: "Counters, stovetop, sink, floor and appliance fronts in one go.",
  },
  {
    id: "clean-bathroom",
    name: "Clean the bathroom",
    category: "general",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "teen",
    description: "Toilet, sink, shower, mirror, floor.",
  },
  {
    id: "do-laundry",
    name: "Do the laundry",
    category: "general",
    frequency: "weekly",
    effort: "long",
    kidFriendly: true,
    minAge: "teen",
    description: "Wash, dry, fold, put away.",
  },
  {
    id: "dust-whole-house",
    name: "Dust the whole house",
    category: "general",
    frequency: "weekly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "wipe-light-switches",
    name: "Wipe light switches and handles",
    category: "general",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  { id: "change-air-filter", name: "Change the air filter", category: "general", frequency: "monthly", effort: "quick" },
  { id: "test-smoke-alarms", name: "Test the smoke alarms", category: "general", frequency: "monthly", effort: "quick" },
  { id: "sort-mail", name: "Sort the mail and paperwork", category: "general", frequency: "weekly", effort: "quick" },
  {
    id: "declutter-10",
    name: "10-minute declutter sweep",
    category: "general",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
    description: "Set a timer, grab a basket, return everything to its home.",
  },
  { id: "clean-windows-outside", name: "Clean the outside of the windows", category: "general", frequency: "occasional", effort: "long" },
  {
    id: "vacuum-stairs",
    name: "Vacuum the stairs",
    category: "general",
    frequency: "weekly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  {
    id: "wipe-doors",
    name: "Wipe doors and door frames",
    category: "general",
    frequency: "monthly",
    effort: "medium",
    kidFriendly: true,
    minAge: "school",
  },
  { id: "clean-fans", name: "Dust ceiling fans and vents", category: "general", frequency: "monthly", effort: "quick" },
  { id: "restock-supplies", name: "Restock cleaning supplies", category: "general", frequency: "monthly", effort: "quick" },
  { id: "pay-bills", name: "Pay the household bills", category: "general", frequency: "monthly", effort: "quick" },
  {
    id: "clean-shared-fridge",
    name: "Clear out the shared fridge",
    category: "general",
    frequency: "weekly",
    effort: "quick",
    description: "Anything unlabelled or expired goes.",
  },
  {
    id: "buy-shared-supplies",
    name: "Buy shared supplies",
    category: "general",
    frequency: "monthly",
    effort: "quick",
    description: "Toilet paper, dish soap, trash bags, sponges.",
  },
  {
    id: "clean-common-areas",
    name: "Clean the common areas",
    category: "general",
    frequency: "weekly",
    effort: "medium",
    description: "Hallway, living room, any space nobody owns.",
  },

  // ---- Pets ------------------------------------------------------------
  { id: "feed-pets", name: "Feed the pets", category: "pets", frequency: "daily", effort: "quick", kidFriendly: true, minAge: "younger" },
  { id: "walk-dog", name: "Walk the dog", category: "pets", frequency: "daily", effort: "medium", kidFriendly: true, minAge: "school" },
  {
    id: "clean-litter-box",
    name: "Clean the litter box",
    category: "pets",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "teen",
  },
  {
    id: "refill-water-bowl",
    name: "Refill the pet water bowl",
    category: "pets",
    frequency: "daily",
    effort: "quick",
    kidFriendly: true,
    minAge: "younger",
  },
  { id: "brush-pet", name: "Brush the pet", category: "pets", frequency: "weekly", effort: "quick", kidFriendly: true, minAge: "school" },
  {
    id: "clean-pet-bed",
    name: "Wash the pet bed",
    category: "pets",
    frequency: "monthly",
    effort: "quick",
    kidFriendly: true,
    minAge: "school",
  },
  { id: "scoop-yard", name: "Scoop the yard", category: "pets", frequency: "weekly", effort: "quick", kidFriendly: true, minAge: "school" },
];

const byId = new Map(CHORES.map((c) => [c.id, c]));

export const getChore = (id: string): Chore | undefined => byId.get(id);
export const getChores = (ids: readonly string[]): Chore[] => ids.map((id) => byId.get(id)).filter((c): c is Chore => Boolean(c));
export const choresByCategory = (category: Chore["category"]) => CHORES.filter((c) => c.category === category);

/** Default wheel shown to first-time visitors. */
export const DEFAULT_WHEEL_IDS = [
  "wash-dishes",
  "vacuum-floors",
  "take-out-trash",
  "clean-bathroom",
  "do-laundry",
  "mop-floors",
  "clean-kitchen",
  "dust-furniture",
  "make-bed",
  "water-plants",
  "clean-fridge",
  "wipe-surfaces",
];
