import type { Template } from "./types";
import { getChores } from "./data";

export const KIDS_SUPERVISION_NOTE =
  "Age groupings are a starting point, not a rule. You know your child, your home and what needs supervising — adjust freely.";

export const TEMPLATES: Template[] = [
  {
    id: "everyday",
    name: "Everyday Household",
    tagline: "The core cleaning chores most homes cycle through every week.",
    group: "household",
    choreIds: [
      "wash-dishes",
      "vacuum-floors",
      "take-out-trash",
      "clean-bathroom",
      "do-laundry",
      "mop-floors",
      "clean-kitchen",
      "dust-furniture",
      "make-bed",
      "water-plants",
      "clean-fridge",
      "wipe-surfaces",
    ],
  },
  {
    id: "quick-10",
    name: "Quick 10-Minute Chores",
    tagline: "Small wins for when you only have a few minutes.",
    group: "household",
    choreIds: [
      "wipe-counters",
      "unload-dishwasher",
      "take-out-trash",
      "make-bed",
      "clean-mirror",
      "water-plants",
      "wipe-light-switches",
      "tidy-entryway",
      "declutter-10",
      "empty-all-bins",
      "clean-microwave",
      "sweep-kitchen",
    ],
  },
  {
    id: "family",
    name: "Family Chores",
    tagline: "A mixed bag of quick and bigger jobs suited to a household with kids and adults.",
    group: "household",
    choreIds: [
      "set-table",
      "clear-table",
      "load-dishwasher",
      "unload-dishwasher",
      "take-out-trash",
      "vacuum-living-room",
      "tidy-living-room",
      "fold-laundry",
      "feed-pets",
      "clean-bathroom",
      "sweep-kitchen",
      "water-plants",
      "make-bed",
      "wipe-surfaces",
    ],
  },
  {
    id: "roommates",
    name: "Roommate Chores",
    tagline: "Shared-apartment responsibilities that are nobody's job until you assign them.",
    group: "situations",
    choreIds: [
      "clean-kitchen",
      "clean-bathroom",
      "take-out-trash",
      "take-out-recycling",
      "vacuum-floors",
      "mop-floors",
      "clean-shared-fridge",
      "buy-shared-supplies",
      "clean-common-areas",
      "wipe-counters",
      "empty-all-bins",
      "bins-to-curb",
    ],
  },
  {
    id: "weekend-reset",
    name: "Weekend Reset",
    tagline: "Everything that puts the house back to zero before Monday.",
    group: "situations",
    choreIds: [
      "change-sheets",
      "wash-bedding",
      "vacuum-floors",
      "mop-floors",
      "clean-bathroom",
      "clean-kitchen",
      "dust-whole-house",
      "clean-fridge",
      "plan-meals",
      "grocery-shopping",
      "tidy-entryway",
      "empty-all-bins",
    ],
  },
  {
    id: "kitchen",
    name: "Kitchen",
    tagline: "Everything from the daily wipe-down to the monthly deep clean.",
    group: "rooms",
    choreIds: [
      "wash-dishes",
      "wipe-counters",
      "clean-stovetop",
      "clean-microwave",
      "clean-sink",
      "sweep-kitchen",
      "mop-kitchen",
      "take-out-trash",
      "wipe-appliances",
      "clean-fridge",
      "clean-oven",
      "organize-pantry",
    ],
  },
  {
    id: "bathroom",
    name: "Bathroom",
    tagline: "The whole bathroom, split into short jobs.",
    group: "rooms",
    choreIds: [
      "clean-toilet",
      "clean-shower",
      "clean-bathroom-sink",
      "clean-mirror",
      "mop-bathroom",
      "restock-toilet-paper",
      "change-towels",
      "empty-bathroom-trash",
      "wash-bath-mat",
      "clean-grout",
      "descale-showerhead",
    ],
  },
  {
    id: "outdoor",
    name: "Outdoor",
    tagline: "Yard, bins and the outside of the house.",
    group: "rooms",
    choreIds: [
      "mow-lawn",
      "rake-leaves",
      "water-garden",
      "pull-weeds",
      "sweep-porch",
      "bins-to-curb",
      "bins-back",
      "wash-car",
      "clean-grill",
      "wipe-outdoor-furniture",
      "shovel-snow",
    ],
  },
  {
    id: "kids-younger",
    name: "Kids: Younger",
    tagline: "Simple, safe, low-stakes tasks — great alongside a grown-up.",
    group: "kids",
    note: KIDS_SUPERVISION_NOTE,
    choreIds: [
      "make-bed",
      "tidy-bedroom",
      "set-table",
      "clear-table",
      "feed-pets",
      "water-plants",
      "put-away-clothes",
      "fold-laundry",
      "organize-shoes",
      "wipe-appliances",
      "dust-furniture",
      "unload-dishwasher",
    ],
  },
  {
    id: "kids-school",
    name: "Kids: School-age",
    tagline: "Real contributions that a child can finish independently.",
    group: "kids",
    note: KIDS_SUPERVISION_NOTE,
    choreIds: [
      "load-dishwasher",
      "unload-dishwasher",
      "take-out-trash",
      "take-out-recycling",
      "vacuum-bedroom",
      "change-sheets",
      "wash-laundry",
      "sweep-porch",
      "walk-dog",
      "clean-bathroom-sink",
      "clean-microwave",
      "water-garden",
      "empty-all-bins",
    ],
  },
  {
    id: "kids-teens",
    name: "Kids: Teens",
    tagline: "Full chores, the same as any adult in the house would do.",
    group: "kids",
    note: KIDS_SUPERVISION_NOTE,
    choreIds: [
      "clean-bathroom",
      "clean-kitchen",
      "do-laundry",
      "cook-dinner",
      "mow-lawn",
      "vacuum-floors",
      "mop-floors",
      "clean-toilet",
      "clean-shower",
      "iron-clothes",
      "clean-litter-box",
      "wash-car",
    ],
  },
  {
    id: "pets",
    name: "Pet Care",
    tagline: "Feeding, walking and cleaning up — the chores that can't be skipped.",
    group: "situations",
    choreIds: ["feed-pets", "refill-water-bowl", "walk-dog", "clean-litter-box", "brush-pet", "clean-pet-bed", "scoop-yard"],
  },
];

export const getTemplate = (id: string) => TEMPLATES.find((t) => t.id === id);
export const templateChores = (t: Template) => getChores(t.choreIds);
export const templatesInGroup = (group: Template["group"]) => TEMPLATES.filter((t) => t.group === group);
